/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tdd.exercises.java;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        new RomanToDecimal().convert("I");
        System.out.println(new App().getGreeting());
    }
}
